### PR TITLE
Check arithmetic operations in finish

### LINKED ISSUE #6: Unchecked arithmetic operations in `finish`
Use checked arithmetic for operations that can fail. In debug mode these cause panics, in release mode they just wrap around.

For example, [this operation](https://github.com/rust-vmm/vm-fdt/blob/13ab882e2f8387753064351c69fbe35c422b448b/src/writer.rs#L312) should use `checked_sub`.

Below it's a regression test that triggers a panic in debug mode:
```rust
    #[test]
    fn test_overflow_subtract() {
        let overflow_size = u32::MAX / size_of::<FdtReserveEntry>() as u32 - 3;
        let too_large_mem_reserve = vec![FdtReserveEntry::default(); overflow_size as usize];
        let mut fdt = FdtWriter::new(&too_large_mem_reserve);
        let root_node = fdt.begin_node("").unwrap();
        fdt.end_node(root_node).unwrap();
        fdt.finish(0x48).unwrap();
    }

```

### PR DESCRIPTION
**Pull request by andreeaflorescu**
This PR addresses a nit (using u32::MAX instead of std::u32::MAX), and fixes #6.

### CODE REVIEW

File: src/writer.rs [hunk 1]
```diff
@@ -802,7 +808,7 @@ mod tests {
 
     #[test]
     fn test_overflow_subtract() {
-        let overflow_size = std::u32::MAX / size_of::<FdtReserveEntry>() as u32 - 3;
+        let overflow_size = u32::MAX / size_of::<FdtReserveEntry>() as u32 - 3;
```
Comment (danielverkamp) [inline src/writer.rs:811]: I used the deprecated form here because the version of Rust in the CI Docker container was too old to support `u32::MAX`, but if it has been upgraded now, this looks good to me.

**Review by danielverkamp — APPROVED** [review]

File: src/writer.rs (hunk 1 above)
Comment (andreeaflorescu) [reply src/writer.rs:811]: It looks like it works with the CI, so I would say to merge it once we get another review.

File: src/writer.rs [hunk 2]
```diff
@@ -333,6 +333,12 @@ impl FdtWriter {
             .try_into()
             .map_err(|_| Error::TotalSizeTooLarge)?;
 
+        // The following operation cannot fail because we previously checked
+        // that both `data.len()` and `strings.len()` fit in a u32, thus
+        // the addition fits in an usize.
```
Comment (lauralt) [inline src/writer.rs:338]: Is this still valid on 32bit platforms? Can those values be somehow close to u32::MAX?

**Review by lauralt — COMMENTED** [review]
Not related to the issue (at least according to its title), but I think there might be some other operations that could benefit from a comment, e.g. https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L194, https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L290. Should we open an issue for them?

File: src/writer.rs (hunk 2 above)
Comment (andreeaflorescu) [reply src/writer.rs:338]: Good catch. I'll use checked add here.

**Comment by andreeaflorescu** [comment]
> Not related to the issue (at least according to its title), but I think there might be some other operations that could benefit from a comment, e.g. https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L194, https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L290. Should we open an issue for them?

The issue was indeed related only to finish, but we can extend it.

For the one related to node_depth, Iwouldn't use checked_add because the increment is only one, the value starts from 0, and you would need to call the `property_*` function `usize::MAX` times for that overflow to be possible.

In `property_array_*` functions we can use a checked arithmetic.

Do you think anything else is worth checking? I looked again and couldn't find anything else.

File: src/writer.rs [hunk 3]
```diff
@@ -287,7 +287,11 @@ impl FdtWriter {
 
     /// Write a property containing an array of 32-bit unsigned integers.
     pub fn property_array_u32(&mut self, name: &str, cells: &[u32]) -> Result<()> {
-        let mut arr = Vec::with_capacity(cells.len() * size_of::<u32>());
+        let size = cells
+            .len()
+            .checked_mul(size_of::<u32>())
```
Comment (danielverkamp) [inline src/writer.rs:292]: I wouldn't object to including this check, but it seems like it should not be possible for it to fail, since `cells` already exists with the corresponding size (maybe it would be clearer to use `std::mem::size_of_val`?)

File: src/writer.rs [hunk 4]
```diff
@@ -296,7 +300,11 @@ impl FdtWriter {
 
     /// Write a property containing an array of 64-bit unsigned integers.
     pub fn property_array_u64(&mut self, name: &str, cells: &[u64]) -> Result<()> {
-        let mut arr = Vec::with_capacity(cells.len() * size_of::<u64>());
+        let size = cells
+            .len()
+            .checked_mul(size_of::<u64>())
```
Comment (danielverkamp) [inline src/writer.rs:305]: Same concern as `property_array_u32` - may be clearer to just use `size_of_val` rather than re-multiplying it.

File: src/writer.rs (hunk 1 above)
Comment (danielverkamp) [reply src/writer.rs:820]: Sounds good, I probably just need to update my local copy of the docker container.

Comment (andreeaflorescu) [reply src/writer.rs:820]: The latest version is `v11`

File: src/writer.rs (hunk 3 above)
Comment (andreeaflorescu) [reply src/writer.rs]: I used `std::mem::size_of_val` as you suggested.

**Review by lauralt — DISMISSED** [review]

**Comment by lauralt** [comment]
> > Not related to the issue (at least according to its title), but I think there might be some other operations that could benefit from a comment, e.g. https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L194, https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L290. Should we open an issue for them?
> 
> The issue was indeed related only to finish, but we can extend it.
> 
> For the one related to node_depth, I wouldn't use checked_add because the increment is only one, the value starts from 0, and you would need to call the `property_*` function `usize::MAX` times for that overflow to be possible.
> 
> In `property_array_*` functions we can use a checked arithmetic.
> 
> Do you think anything else is worth checking? I looked again and couldn't find anything else.

I would still leave a comment for the following: https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L170, https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L194, https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L208 explaining why they can't overflow/underflow.

File: coverage_config_x86_64.json [hunk 5]
```diff
@@ -1,5 +1,5 @@
 {
-  "coverage_score": 91.7,
+  "coverage_score": 91.8,
```
Comment (danielverkamp) [inline coverage_config_x86_64.json:2]: The coverage number probably needs to be updated since #11 was merged.

**Review by danielverkamp — APPROVED** [review]

File: coverage_config_x86_64.json (hunk 5 above)
Comment (lauralt) [reply coverage_config_x86_64.json]: Hi, Andreea is on vacation. I just pushed the required coverage update and added one commit with a few comments regarding the safety of some operations.
I'm still not sure if [this](https://github.com/rust-vmm/vm-fdt/blob/master/src/writer.rs#L241) can never panic, I think I would still use `checked_add` here :-?. Thoughts?

**Review by lauralt — DISMISSED** [review]

**Comment by andreeaflorescu** [comment]
@danielverkamp can you take another look please?

**Review by lauralt — APPROVED** [review]

File: src/writer.rs [hunk 6]
```diff
@@ -386,6 +386,13 @@ impl FdtWriter {
             .try_into()
             .map_err(|_| Error::TotalSizeTooLarge)?;
 
+        let totalsize = self
+            .data
+            .len()
+            .checked_add(self.strings.len())
+            .ok_or(Error::TotalSizeTooLarge)?;
+        let totalsize = totalsize.try_into().map_err(|_| Error::TotalSizeTooLarge)?;
```
Comment (alexandruag) [inline src/writer.rs:394]: Just as a remark/point of view, I think that code is clearer when using `T::try_from` instead of `x.try_into`, just so it's easier for the reader to see what type are we converting into, and also ensures we don't actually convert into something else by accident.

**Review by alexandruag — APPROVED** [review]
Looks good, just left an FYI comment.

File: src/writer.rs (hunk 6 above)
Comment (andreeaflorescu) [reply src/writer.rs:394]: We're using try_into throughout the code. I generally agree with what you are saying, but I don't think it applies here because we call into a function which receives `u32` as a parameter. I'll leave it as is for now.

**Review by alexandruag — APPROVED** [review]

**Review by lauralt — APPROVED** [review]

**Review by alexandruag — APPROVED** [review]
